-- premake5.lua
-- generated by muhhae

workspace "CPPTemplate"
    configurations { "Debug", "Release" }

SRCDIR = "src" --Source Code Directory
BUILDDIR = "build" --Build Directory
OBJDIR = "%{BUILDDIR}/obj" --Obj Directory


project "muhhae"
    kind "ConsoleApp" --App Type
    language "C++" --Languange

    buildoptions {"-std=c++23", "-Wall"} --CXXFLAGS

    targetdir "%{BUILDDIR}/%{cfg.buildcfg}" --LDFLAGS
    objdir "%{OBJDIR}/%{cfg.buildcfg}"

    prebuildcommands

    files {
        "%{SRCDIR}/**.h",
        "%{SRCDIR}/**.hpp", 
        "%{SRCDIR}/**.cpp"
    }

    filter "configurations:Debug"
        defines { "DEBUG" }
        symbols "On"

    filter "configurations:Release"
        defines { "RELEASE" }
        optimize "On"