-- premake5.lua
-- generated by muhhae

workspace "ImguiApp"
    configurations { "Debug", "Release" }

SRCDIR = "src" --Source Code Directory
BUILDDIR = "build" --Build Directory
OBJDIR = "obj" --Obj Directory
RESFILE = "resource" --Resource Directory
INCLUDEDIR = "include" --include directory for external library


project "ImguiApp"
    language "C++" 
    cppdialect "C++latest"

    links {
        "opengl32","sfml-audio", "sfml-graphics", "sfml-network", "sfml-system", "sfml-window"
    }

    targetdir "%{BUILDDIR}/%{cfg.buildcfg}" 
    objdir "%{OBJDIR}/%{cfg.buildcfg}"

    includedirs {
        "%{INCLUDEDIR}/**"
    }

    files {
        "%{SRCDIR}/**.h",
        "%{SRCDIR}/**.hpp", 
        "%{SRCDIR}/**.cpp",


        "%{INCLUDEDIR}/**.cpp",
        "%{INCLUDEDIR}/**.h",
        "%{INCLUDEDIR}/**.hpp"
    }

    prebuildcommands { 
        "rm -rf %{BUILDDIR}/%{cfg.buildcfg}/%{RESFILE}",
        "{COPYDIR} %{RESFILE} %{BUILDDIR}/%{cfg.buildcfg}/%{RESFILE}" 
    }

    filter "configurations:Debug"
        kind "ConsoleApp"
        defines { "DEBUG" }
        symbols "On"

    filter "configurations:Release"
        kind "WindowedApp"
        defines { "RELEASE" }
        optimize "On"